// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Turntablio.RoleService.Data.Model;

namespace Turntablio.RoleService.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200407133052_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Turntablio.RoleService.Data.Model.Employee", b =>
                {
                    b.Property<int>("employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("employeeaddress")
                        .HasColumnType("text");

                    b.Property<string>("employeeemail")
                        .HasColumnType("text");

                    b.Property<string>("employeefname")
                        .HasColumnType("text");

                    b.Property<string>("employeelname")
                        .HasColumnType("text");

                    b.Property<string>("employeerole")
                        .HasColumnType("text");

                    b.HasKey("employeeid");

                    b.ToTable("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
